# C-b is not acceptable -- Vim uses it
set-option -g prefix C-a
bind-key C-a last-window

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Set status bar
set -g status-bg black
set -g status-fg white
set -g status-left ""
set -g status-right "#[fg=green]#H"

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Activity monitoring
#setw -g monitor-activity on
#set -g visual-activity on

# Example of using a shell command in the status line
#set -g status-right "#[fg=yellow]#(uptime | cut -d ',' -f 2-)"

# Highlight active window
set-window-option -g window-status-current-bg red

set-window-option -g mode-keys vi

new-session -s yprox -n vim "cd ~/www/yProx; bash -i"
new-window -t yprox -n shell 

new-session -s logs -n top "top"
new-window -t logs -n apache-error "tail -fn 100 /var/log/apache2/error.log"
new-window -t logs -n mysql "tail -fn 100 /var/log/mysql/mysql.log"
new-window -t logs -n yprox-admin-dev "tail -fn 100 ~/www/yProx/apps/admin/logs/dev.log"
new-window -t logs -n yprox-admin-prod "tail -fn 100 ~/www/yProx/apps/site/logs/dev.log"
new-session -s tasks "vim ~/Dropbox."
set-option -g tasks default-path ~/Autosync/Documents

new-session -s system -n system

attach -t yprox
